name: minichallenge3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-174.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  go_router: ^6.5.9
  provider: ^6.0.3
  url_launcher: ^6.1.5
  tmdb_api: ^2.1.5
  json_annotation: ^4.6.0
  file: ^6.1.4
  cached_network_image: ^3.3.0
  google_fonts: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
